### ISSUE TITLE
ヤバいわよ！！画像を発言させたい

### ISSUE THREAD

**Issue by yuiseki** [arakawatomonori/kyaru#20]
- yabai
 - やば
 - ヤバ

という文字列を含む発言があったら、
そのチャンネルにヤバいわよ！！画像を発言させたい。

**Comment by takano32** [comment]
こっちどうですか。

https://i.gyazo.com/32b76d54f58091042676530a37fcd6bf.gif


![zmzAyuK](https://user-images.githubusercontent.com/16088/64910264-49ad6780-d74f-11e9-91f7-e0e8e1505a6b.gif)
