### ISSUE TITLE
キャルちゃんにストレス機能を実装したい

### ISSUE THREAD

**Issue by ao-spirogyra** [arakawatomonori/kyaru#36]
無理をいいすぎるとストレスが溜まって爆発する

他の機能全部と関連しそうなのでめんどくさそう
![](https://imasoku.com/wp-content/uploads/2019/03/sL44FmR.jpg)

**Comment by ao-spirogyra** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwjr_sDwmNXkAhW7JaYKHemlAlEQjRx6BAgBEAQ&url=http%3A%2F%2Fpetiroworld.jp%2Fblog-entry-4363.html&psig=AOvVaw1TLpU45SU44Zl4gPQkeN_R&ust=1568718208949891

**Comment by yuiseki** [comment]
#69 でstressテーブルはつくった

**Comment by yuiseki** [comment]
#71 で着手した

**Comment by yuiseki** [comment]
#71 でストレス値を増減できるようになった

**Comment by yuiseki** [comment]
とりあえず労働したらストレスが溜まる、寝るとストレスが減る、というロジックにした
